### ISSUE TITLE
Feature: Disable Authentication

### ISSUE THREAD

**Issue by meichthys** [matteo-convertino/otpmanager-nextcloud#16]
Perhaps there's a security issue to prevent this, but would be nice if it could be disabled in order to rely on Nextcloud's built-in authentication/2fa/security features to protect access to the otpmanager app.

**Comment by meichthys** [comment]
@matteo-convertino  Sorry, this belongs on the server component, Can you move it?

**Comment by meichthys** [comment]
Also, (if possible) it would be nice if the Password field was auto-focused to prevent the user from having to click into the field before typing). 

Very petty (i know), but it would streamline the login process when logging in and out often.

**Comment by matteo-convertino** [comment]
Regarding the password I can tell you that right now it cannot be disabled, because it was designed to protect the accounts even during communication/synchronization with the app and to not have the secret keys in clear text on the database.

I like petty things (it's the little details that make the difference). It is very useful to have the password field auto focus.

**Comment by meichthys** [comment]
Totally understandable. Thanks for the clarification.

**Comment by matteo-convertino** [comment]
I just published the [release](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.3.5) with the possibility to remember the password, so as not to enter it every time, and with autofocus on the text input of the password.

**Comment by meichthys** [comment]
Great to see all these improvements being implemented. Great work!
