### ISSUE TITLE
[Bug] `Show Codes` Setting does not stay selected

### ISSUE THREAD

**Issue by meichthys** [matteo-convertino/otpmanager-nextcloud#7]
The `show codes` option in the settings does work as expected, but it does not stay selected. 
After reloading the page, the option is turned off.

![image](https://github.com/matteo-convertino/otpmanager-nextcloud/assets/10717998/28d3658d-570d-4b7c-8d8b-69690ed6db84)

**Comment by matteo-convertino** [comment]
Right now the `show codes` value is stored only on the frontend side.
The change I postponed (because I didn't consider it important for the purposes of launching the extension) is to add another table in the db called, for example, `otpmanager_user_settings` which stores the value of `show_codes` and other user preferences that will occur in the future.

**Comment by meichthys** [comment]
Ok, I figured that might be the case. Great work!

**Comment by matteo-convertino** [comment]
This bug should be fixed with the [release](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.2.0). If the problem persists feel free to reopen the issue.
